pr2eus/pr2-interface.l
add make-plan function for move base planner returning result without really moving the robot.
when solving ik with move base enable, we may use it to check whether the real robot can go to that place or not..
and i make the return coords sequence reference to (send *pr2* :worldcoords), is this a good manner?
=> add make-plan method for move base

pr2eus/robot-interface.l
* smoothな動作を実現するための便利関数
: wait-interpolation-smooth (time-to-finish &optional (ctype))
angle-vector で指定した秒数よりtime-to-finish秒だけ早く抜ける。
　angle-vectorで3000と設定して、time-ti-finishを1000とした場合2秒で抜ける。
: interpolationp
動作が終了しているかどうかのみ判定して抜ける
=> Add interpolation smooth

pr2eus/robot-interface.l
* controller-action-clientで生じたエラーの修正
goalを送っていないのにfeedback-cbが呼ばれてしまうことがあるようで、(send ros::comm-state :action-goal)がnilなのにメソッドを要求してしまいエラーを吐いていたようです。
=> fix actionlib error

pr2eus/robot-interface.l
From https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/85#issuecomment-71589199
modiied and now we can use as below
```
(send *ri* :angle-vector-sequence (list av1 av2 av3) (list :fast 4000 nil))
(send *ri* :angle-vector-sequence (list av1 av2 av3) (list :fast :fast :test))
[ERROR] [1422533494.154349018]: :angle-vector-sequence tm is invalid.  args: 1000.0
irteusgl 0 error:  :angle-vector-sequence tm is invalid. args: 1000.0 in (error ":angle-vector-sequence tm is invalid. args: ~A" tm)
```
=> modify :angle-vector-sequence to use :angle-vector-duration

pr2eus/robot-interface.l
This change may affects on baxter interface.
So please change :scale of baxter's angle-vector to 5 @aginika 
ref: https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/120
=> change default 5 to 1 as :scale in angle-vector

pr2eus/pr2-interface.l
service call '/move_base_node/clear_unknown_space' is now deprecated.
=> [pr2-interface.l] remove unused service call 

pr2eus/robot-interface.l
Smooth angle-vector may have short duration for each angle-vector, so :angle-vector-sequence should use :min-time=0.0
=> [pr2eus] :min-time=0.0 in :angle-vector-sequence

pr2eus/robot-interface.l
angle-vector-sequence の最後の姿勢を publish-joint-state して kinematics simulator を draw-objcects する変更を加えました。
* test code
```
(hrp2jsknt-init)
(setq *robot* *hrp2jsknt*)
(send *ri* :angle-vector-sequence
(list
(copy-seq (send *robot* :reset-pose))
(copy-seq (send *robot* :reset-manip-pose))
(copy-seq (send *robot* :reset-pose))
(copy-seq (send *robot* :reset-manip-pose))
(copy-seq (send *robot* :reset-pose))
(copy-seq (send *robot* :reset-manip-pose)))
(list
100 100
100 100
100 100))
(v- (send *robot* :angle-vector) (send (send *ri* :get-val 'robot) :angle-vector)) ;; equal zero
(v- (send *ri* :state :potentio-vector) (send (send *ri* :get-val 'robot) :angle-vector))) ;; equal zero
(v- (send *robot* :angle-vector) (send (send *ri* :get-val 'robot) :angle-vector))  ;; not zero !!!
```
=> angle-vector-sequence の最後の姿勢が kinematics simulator で若干ずれる

pr2eus/robot-interface.l
=> 	[pr2eus] Fix :interpolatingp by using ros::*simple-goal-state-active* instead of actoinlib_msgs::GoalStatus::*active*

pr2eus/robot-interface.l
update joint defined in conroller type, only for simulation see #135
8bbb993 may change current behavior, 
current : update all joint even if not listed on contrller type 
next : update joint only within controlle type
- [robot-interface.l] update joint in (*ri* . robot) only in controller-type
- [robot-interface.l] update only cotroller joint for simulation mode
=> update joint only in contrller-type for simulation mode

pr2eus/pr2-utils.l
This PR is necessary to do following
https://github.com/jsk-ros-pkg/jsk_model_tools/issues/119#issuecomment-114086317
```
2 use arm end coords but set small weight ( I suppose use greater number for eus arguments?) not to move
arms . Of cause, arm initial arm postures is set to grab object no the ground. From the kinematics point of 
view, this is almost equals to 1. So it should move.
```
@aginika
=> [pr2eus] pass additional-weight-list when calling super class method

pr2eus/pr2-interface.l
please check this on real robot @h-kamada
=> pr2-interface.l: add :go-pos-unsafe, :go-pos-unsafe-no-wait, :go-pos-unsafe-wait

pr2eus/pr2-interface.l, pr2eus/robot-interface.l, pr2eus/test/default-ri-test.l, pr2eus/test/pr2-ri-test-simple.l
- pr2-interface : support timer-based motion for :move-to
- test/default-ri-test.l: add test code for :wait-interpolation-smooth, #158
- more realistic simulation mode
-  pr2-interface.l: add :go-pos-unsafe, :go-pos-unsafe-no-wait,  :go-pos-unsafe-wait
=> add more realistic simulation mode  rev 2

.travis.yml, pr2eus/pr2-interface.l, pr2eus/test/pr2-ri-test-simple.l
current implementation in simulationp is not correct, it always move to coordinates relative to current robot position, but that depends on `frame-id` arguments
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/d90a80e00a6aa03ad7fa632cf40551c13e2dc75b/pr2eus/pr2-interface.l#L394
=> Fix :move-to in sim mode (check frame-I'd) add test for :move-to

pr2eus/robot-interface.l
go-* function is currently implemnted in https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/pr2-interface.l#L485 or https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L713
the motivation of this PR is write template function in robot-interface.l and define API
=> robot-interface.l: add go-* function prototype

pr2eus/speak.l
**SUMMARY**
- by setting `t`/`nil` for variable `*speak-wait*`, we can change default behavior of speak function
**EFFECT**
global variable `*speak-wait*` is defined.
=> [pr2eus/speak.l] add default variable for waiting speak

pr2eus/robot-interface.l
**SUMMARY**
- add keyword option `:look-all` to `:draw-objects` method of `robot-interface` class.
- This PR does not change default behavior.
- This PR fixes #179 by passing `(send *ri* :set-simulation-default-look-at nil)`
=> [pr2eus/robot-interface.l] add option :look-all when :draw-objects

pr2eus/robot-interface.l
https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/183
```send *ri* :state :effort-vector``` で joint_statesのeffortを返すようにしました。
=> add :effort-vector for reading effort of joint_states

pr2eus/robot-interface.l
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/188
はまだ途中だったのですがmergeされてしまったので、
以下で修正しました。
`:state`系の`:torque-vector`をよんだときに、逆動力学計算せず
torque-vectorをもってくるようになります。
upstream側は、影響する範囲を調べて直して、、、がまだかかりそうです
https://github.com/euslisp/jskeus/issues/94
@YoheiKakiuchi , @garaemon 
確認してもらえると助かります。
=> Revert https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/188 and fix :torque-vector to return joint torques.

pr2eus/pr2-interface.l, pr2eus/test/pr2-ri-test-simple.l
* check whether PR2 is moving
* In simulation mode, just return nil
=> [pr2eus] add :go-waitp

pr2eus/pr2-interface.l, pr2eus/robot-interface.l
**NOTICE**
This PR changes return value of `:wait-interpolation`
**SUMMARY**
the return value of `:wait-interpolation` is defined in docs as below:
> return values is a list of interpolatingp for all controllers, so (null (some #'identity (send *ri* :wait-interpolation))) -> t if all interpolation has stopped
but on real robot it returns `(send-all controller-actions :wait-for-result))`
So I fixed according with docs.
tested on pr2-simulator and pr1012 real robot.
discussed at https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/187
=> [pr2eus/robot-interface.l, pr2eus/pr2-interface.l] fix: :wait-interpolation returns :interpolatingp on real robot

pr2eus/pr2-interface.l, pr2eus/robot-interface.l
- check if move-base-trajectory-action is available
- move odom-callback to robot-move-base-interface.l
- enable to set base_footprint name
=> robot-interface.l: fix robot-move-base-interface

pr2eus/robot-interface.l
- robot-interface.l: fix clear-costmap/change-inflation-range to support different move_base node name
=> clear-costmap for custom move_base node name

pr2eus/CMakeLists.txt, pr2eus/package.xml, pr2eus/robot-interface.l, pr2eus/test/robot-init-test.l, pr2eus/test/robot-init-test.test
Add robot init function to create `*ri*` and robot instance according to the following discussion:
https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/175
* Behavior
1. Without /robot/type and argument, or no interface file is found, robot instance and interface instance are not created and errors are invoked.   
`(robot-init) ;; without ros param` -> error.
2. If argument are specified and robot interface file is found, robot instance and interface with given name are created.   
`(robot-init "pr2")` -> OK
3. If no argument is specified, /robot/type ROSPARAM is set, and robot interface file is found, robot instance and interface with given name are created.  
`(robot-init) ;; with /robot/type setting` -> OK. Create `*ri*` and robot from /robot/type.
* Typical usage:
```
(robot-init) ;; With …
```
=> Add robot init function to create *ri* and robot instance

pr2eus/pr2-utils.l
* add `:start-grasp` , `:stop-grasp` method for \*pr2\*
* `:gripper` method is overwritten in pr2-util.l, so couldn't write these codes in irtrobot.l
=> [pr2eus] add start-grasp, stop-grasp for *pr2*

pr2eus/robot-interface.l
This probrem is reported on Baxter robot with custom gripper hand, which had two different node publishing `joint_states`
- realtime_loop for baxter joints ~100 hz
- gripper node for girpper joint ~10 hz
Since we set queue size of `joint_states` as 1, and when ever we call `send *ri* :state` (or `:spin-once`) it may fail to get baxter joints.
From our experiments, when we run our main loop at 10hz, usually `:state` read data from `realtime_loop`, but at some point it reads gripper node for several sequences
```
(ros-state-call-back seq 52764151 stamp #<ros::time #X1c4fcb70 1464165319.524> position #f(0.0 -2.52686 -94.5264 134.626 97.4268 -2.39502 91.3843 10.2393 0.0 104.546 68.9062 -19.5996 48.7793 -71.5649 -14.1724 -66.2915))
(ros-state-call-back seq 52764161 stamp #<ros::time #X2074fc48 …
```
=> robot-interface.l : add option to set queue size for /joint_state subscriber

pr2eus/robot-interface.l
for https://github.com/start-jsk/rtmros_common/pull/957
=> fix :wait-interpolation-smooth for pr2_controllers_msgs/JointTrajectoryActionFeedback

.travis.yml, pr2eus/CMakeLists.txt
Latest `catkin_tools` has become to consider arguments of `catkin_package` in `CMakeLists.txt`.
build of `jsk_roseus` fails with error on this package.
```bash
[pr2eus] WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
[pr2eus] WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
[pr2eus] -- [roseus.cmake] pr2eus depends on audio_common_msgs;std_msgs;actionlib_msgs;diagnostic_msgs;geometry_msgs;nav_msgs;pr2_msgs;rosgraph_msgs;roscpp;actionlib;actionlib_tutorials;dynamic_reconfigure;move_base_msgs;sensor_msgs;shape_msgs;sound_play;std_srvs;tf;tf2_msgs;topic_tools;trajectory_msgs;control_msgs;pr2_controllers_msgs;visualization_msgs
[pr2eus] …
```
=> [pr2eus/CMakeLists.txt] remove unused variable from catkin_package

pr2eus/speak.l
In eus test environment, sound play action server does not exists.
In this case timeout must be small not to wait action server.
=> [pr2eus/speak.l] add *speak-timeout* param to wait action server

pr2eus/pr2-interface.l, pr2eus/robot-interface.l
this change requires
https://github.com/jsk-ros-pkg/jsk_robot/pull/623
=> [pr2eus/robot-interface.l] use follow joint trajectory action

pr2eus/pr2-utils.l
This is to fix the problem discussed in https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/206
=> Include redundant links when calculate collision

pr2eus/robot-interface.l
related to https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/237#issuecomment-253728720 and https://github.com/start-jsk/rtmros_common/pull/970#issuecomment-253446024.
one of this PR or https://github.com/start-jsk/rtmros_common/pull/970 should be merged.
check result of whether hrp2jsk-init works or not:
- pr2eus (latest origin/master), hrpsys_ros_bridge (latest origin/master): not work
- pr2eus (This PR), hrpsys_ros_bridge (latest origin/master): work
- pr2eus (latest origin/master), hrpsys_ros_bridge (https://github.com/start-jsk/rtmros_common/pull/970) work
=> [pr2eus/robot-interface.l] update actionlib name of default controller.

pr2eus/pr2-interface.l
In current implementation, if no object is touched with gripper, the object is not get `:assoc`.
**BEFORE**
```lisp
(load "models/room73b2-mug-cup-object.l")
(load "package://pr2eus/pr2-interface.l")
(pr2-init)
(setq cup (room73b2-mug-cup))
(send cup :translate #f(700 0 900))
(send cup :rotate pi/2 :z)
(objects (list cup *pr2*))
(send *ri* :objects (list cup))
(send *ri* :stop-grasp :rarm)
(seond *pr2* :rarm :inverse-kinematics (car (send cup :handle)))
(send *ri* :start-grasp :objects (send *ri* :find-object cup))
(send *ri* :robot :rarm :end-coords :descendants) ;; => returns nil, because cup handle is not touched gripper surface
```
**AFTER**
- assoc object if gripper is closed
- print warning if no object is touched.
```lisp
;; same as above
(send *ri* :start-grasp :objects (send *ri* …
```
=> [pr2-interface.l] grasp object even if no collision with gripper

pr2eus_moveit/euslisp/robot-moveit.l
set `controller-type` for `:angle-vector-motion-plan` 
Issues: https://github.com/jsk-ros-pkg/jsk_robot/issues/722
Related to https://github.com/jsk-ros-pkg/jsk_robot/issues/722#issuecomment-261752500
=> [pr2eus_moveit] add :ctype args in angle-vector-motion-plan

pr2eus_moveit/euslisp/robot-moveit.l
- modify `:angle-vector-motion-plan` to accept angle-vector-sequence
- set `(butlast avs)` as trajectory constraints
I checked with real robot and it works
=> [pr2eus_moveit] modify :angle-vector-motion-plan to accept angle-vector-sequence

pr2eus_moveit/euslisp/collision-object-publisher.l
From #265
- remove unused `object-frame-id` in `collision-object-publisher`
=> [pr2eus_moveit] remove unused key in collision-object-publisher

pr2eus/robot-interface.l
I have noticed that many people did not noticed that robot-interface intentionally started kinematics simulator, so display that with the reason.
=> add more message on kinematics simulator mode

pr2eus_moveit/euslisp/robot-moveit.l
- `angle-vector-motion-plan` return `(list av)` 
currently it returns `(nil nil nil nil nil)`
=> [pr2eus_moveit] angle-vector-motion-plan return angle-vector

pr2eus_moveit/euslisp/collision-object-publisher.l
What changed
- support body class object, which do not have `:bodies` method.
=> [pr2eus_moveit/collision-object-publisher] support body class object

pr2eus_moveit/euslisp/robot-moveit.l
solve: https://github.com/start-jsk/jsk_apc/issues/1989
this cause baxter arm jerky arm motion.
`send-trajectory` `starttime` should be equal to `angle-vector-motion-plan`'s' `start-offset-time` (according to `angle-vector` https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L395)
=> [pr2eus_moveit] pass start-offset-time as starttime to :send-trajectory

pr2eus_moveit/euslisp/robot-moveit.l
set default planner-id when moveit environment is initialized
=> [pr2eus_moveit] set default planner in moveit-env initialization

pr2eus/pr2-interface.l, pr2eus/robot-interface.l
When `tf2` is used instead of `tf` (e.g. init with `:use-tf2 t` in `pr2-interface`), following error occurs:
This is because of difference:
`tf` style: `/world/hoge`
`tf2` style: `world/hoge`
```bash
Warning: Invalid argument "/map" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like: 
at line 130 in /tmp/binarydeb/ros-indigo-tf2-0.5.14/src/buffer_core.cpp
Warning: Invalid argument "/map" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like: 
at line 130 in /tmp/binarydeb/ros-indigo-tf2-0.5.14/src/buffer_core.cpp
...
```
I removed the first character `/` from frames and checked it works both `tf` and `tf2` system.
I suggest that merge this pull request first and revert if something fails.
=> [pr2eus] fix: remove the first '/' from frame

pr2eus/robot-interface.l, pr2eus_moveit/euslisp/robot-moveit.l
- [pr2eus] use only controller-type in send-trajectory
- [pr2eus_moveit] 	pass ctype in angle-vector-motion-plan
Fixes https://github.com/jsk-ros-pkg/jsk_robot/issues/776
@k-okada
I searched about `:send-trajectory`, but I didn't understand the reason why it has `controller-type` and `controller-action`.
My opinion is `controller-type` is necessary, and `controller-action` depends on it, as my first commit https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/292/commits/d8b0aa6802ccc9f113a9aad8123221cc967004b2.
I'm afraid if this commit breaks API, but I couldn't find out other method which uses `:send-trajectory`.
cc. @Affonso-Gui
=> [pr2eus][pr2eus_moveit] use ctype in :send-trajectory and pass ctype in angle-vector-motion-plan

pr2eus/CMakeLists.txt, pr2eus/package.xml, pr2eus/pr2-interface.l
This PR is refactored version of #281.
Added methods for switching controllers:
```lisp
2.irteusgl$ send *ri* :list-controllers
(("base_controller" . t) ("base_odometry" . t) ("head_camera_trigger" . t) ("head_traj_controller" . t) ("head_traj_controller_loose") ("l_arm_controller"\
. t) ("l_arm_controller_loose") ("l_forearm_cam_trigger" . t) ("l_gripper_controller" . t) ("l_gripper_sensor_controller" . t) ("laser_tilt_controller" .\
t) ("projector_controller" . t) ("projector_trigger" . t) ("prosilica_inhibit_projector_controller" . t) ("r_arm_controller" . t) ("r_arm_controller_loos\
e") ("r_forearm_cam_trigger" . t) ("r_gripper_controller" . t) ("r_gripper_sensor_controller" . t) ("torso_controller" . t))
3.irteusgl$ send *ri* :start-mannequin-mode 
[ INFO] [1495346022.892181125]: …
```
=> [pr2eus][pr2-interface.l] add switch-controller methods

pr2eus_moveit/euslisp/robot-moveit.l
When `max_velocity_scaling_factor`  and `max_acceleration_scaling_factor` is `1.0` in  `MotionPlanRequest`, it is same as `:fast` in `:angle-vector-raw`
- support tm `:fast` in `:angle-vector-motion-plan`
- add `:scale` key in `:angle-vector-motion-plan`
- add `trajectory_constraints` comment out
- add `max_velocity_scaling_factor` and `max_acceleration_scaling_factor` key
=> [pr2eus_moveit] support tm :fast in :angle-vector-motion-plan

pr2eus/make-pr2-model-file.l, pr2eus/test/make-pr2-model-file-test.l
rewrited version of #300
- remove make-camera-from-ros-camera-info-aux, it is defined in roseus 1.0.1
- [pr2eus/pr2.l] update make-camera-from-ros-camera-info-aux
=> use make-caemra-from-ros-camera-info-aux inroseus, in order to generate pr2 model corresponding to jsk-ros-pkg/jsk_roseus#526

pr2eus_moveit/euslisp/robot-moveit.l
- Fix typo:
- `controller-type` -> `ctype`
cc. @pazeshun
=> [pr2eus_moveit] fix typo in robot-moveit.l

pr2eus_moveit/euslisp/robot-moveit.l
```lisp
(when (and total-time ;; [msec]
(< orig-total-time
(/ total-time 1000)))
```
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/0.3.10/pr2eus_moveit/euslisp/robot-moveit.l#L541-L543
=> [pr2eus_moveit] fix typo in total-time condition

pr2eus_moveit/euslisp/robot-moveit.l
error occur when `(length controller-actions) != (length (send self ctype))`.
this case happens when you init robot-interface with `:default-controller`,
but send `av` with `:rarm-controller`.
=> [pr2eus_moveit] fix bug in angle-vector-motion-plan

pr2eus_moveit/euslisp/robot-moveit.l, pr2eus_moveit/test/test-pr2eus-moveit.l
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/310#issuecomment-314694668
CAUTION: 21ed50b changes to set start-offset-time to 0 as default value, other wise, if we do not set this value, we'll skip trajectory-filter very easily 
```
(:trajectory-filter ;; simple trajectory for zero duration
(traj &key (copy) (total-time 5000.0) (minimum-time 0.001) (start-offset-time) (clear-velocities) &rest args &allow-other-keys)
(let ((orig-total-time (send (send (car (last (send traj :points))) :time_from_start) :to-sec)))
(when (and minimum-time (not start-offset-time)
(> orig-total-time
minimum-time))
(ros::ros-warn ";; Trajectory Filter will not work, start-offset-time : ~A, minimum-time : ~A, first point in trajectory ~A" start-offset-time minimum-time orig-total-time)
(return-from …
```
=> add test for https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/310#issuecomment-314694668

pr2eus/robot-interface.l, pr2eus/speak.l, pr2eus/test/speak-test.l
Also addressed in https://github.com/jsk-ros-pkg/jsk_robot/pull/833
This PR includes:
- Cleanup unused text-to-speech methods
- Add text-to-speech method caller to robot-interface
=> pr2eus: add text-to-spech method to robot-interface

pr2eus/robot-interface.l, pr2eus/speak.l, pr2eus/test/speak-test.l, pr2eus/test/speak-test.test
revrited version of #331, we need `(speak-jp)` withiht `*ri*`
- sound_play could not run within travis/jenkins, so use hztest aso dummy subscriber
- pr2eus: integrate speak function
- Revert "pr2eus: add text-to-spech method to robot-interface (#318)"
This reverts commit ecb2a1e29d2d56ae16035064c91617f2b0afa786.
=> pr2eus: partially rever speak function

pr2eus/pr2-interface.l, pr2eus/robot-interface.l
Fixing some problems in :end-coords-interpolation.
Namely,
1. Does not behave properly when over-360 degree turns are present. This is because pr2-interface splits the angle vector in its midpoints, which is not what we want to do in :end-coords-interpolation.
2. Move only in 50 ms when all end-coords are the same.
3. IK usually fails when the head moves. Dealing with it by having :head and :torso move by midpoint vector, instead of IK.
4. It actually does not send designed angle-vector in the end.
5. Solving IK in order may cause arms IK to change desired torso position. Adding :use-torso nil.
This problems can be reproduced with
```
(setq vec #f(50.0 47.7222 12.2897 117.176 -106.014 -77.3995 -76.8709 -105.904 -47.7222 12.2897 -117.176 -106.014 77.3995 -76.8709 105.904 0.0 0.0)
v0 …
```
=> Fix :end-coords-interpolation problems

.travis.yml, pr2eus/package.xml, pr2eus/pr2-interface.l, pr2eus/test/pr2-ri-test.l, pr2eus/test/pr2-ri-test.launch
Since pr2_gazebo for kinetic was released early 2018, travis failed in kinetic test (https://travis-ci.org/jsk-ros-pkg/jsk_pr2eus/builds/361065737, https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/337)
It seems `start-grasp` never returns because of weak effort? or never detected stall situation.
This might be not a good solution, we need to more better simualtion of gripper. For example we set 5000 effort for simulation, but real robot uses ~25.
=> increase stall_velocity_threshold to pass grasp test

pr2eus/robot-interface.l
- `:go-pos-unsafe` internally computes the duration of base movement given a goal and slow the motion if it is less than 1000 msec (for safety reason, I guess), but the duration is still left original value so the goal is never reached.
- `:move-trajectory`: documentation says 
```lisp
(:move-trajectory
(x y d &optional (msec 1000) &key (stop t) (start-time) (send-action nil))
" x [m/sec] y [m/sec] d [rad/sec] msec [milli second]
```
But it also accepts `list` for `x` and `y` but in that case, `x` is assumed as the list of `#f(x y d)` , y for list of `time[msec]`, and then `d` and `msec` are ignored!
This is really confusing...
It looks it is the function that `:move-trajectory-sequence` should have, so I moved the functionality to `:move-trajectory-sequence`.
And I also fixed some parts …
=> Fix wrong behaviors in :go-pos-unsafe / :move-trajectory / :move-trajectory

pr2eus/test/make-pr2-model-file-test.l
I'm afraid euscollada 0.4.0 has some changes on pr2eus test code
c.f. https://github.com/jsk-ros-pkg/jsk_model_tools/pull/216 ? https://github.com/jsk-ros-pkg/jsk_model_tools/pull/212 ?
https://api.travis-ci.org/v3/job/410247467/log.txt
```
[pr2eus.rosunit-make_pr2_model_file_test/test-link][FAILURE]--------------------
Test:(= (norm (send (send link-unstable :worldcoords) :difference-position (send link-stable :worldcoords))) 0.0)
Trace:"^[0mmstart testing [test-link]
vector]
pr2eus/build/pr2eus/test_results/pr2eus/rosunit-make_pr2_model_file_test.xml
"
Message:"check link position #<bodyset-link #X602b028 head_pan_link  -67.07 0.0 1222.125 / 0.0 0.0 0.0> #<bodyset-link #X8da6040 head_pan_link  -67.07 0.0 1222.125 / 0.0 0.0 0.0>" …
```
=> euscollada 0.4.0 requries changes in tests

.travis.yml, pr2eus/robot-interface.l, pr2eus_moveit/CMakeLists.txt, pr2eus_moveit/euslisp/pr2eus-moveit.l, pr2eus_moveit/euslisp/robot-moveit.l
This PR contains:
- `pr2eus`:
- Add optional argument for joint names of base trajectory action goal
- `pr2eus_moveit`:
- take `multi_dof_joint_state` into account (formerly ignored)
- run `:trajectory-filter` on any planning time
- Adds support of motion planning for robots with mobile base. (added methods for `robot-move-base-interface`)
- Run `pr2eus_moveit` test as possible (formerly, it is only tested on indigo)
- `.travis.yml`:
- Enable test for `pr2eus_moveit` on kinetic
=> pr2eus_moveit: support motion with mobile base

pr2eus_moveit/euslisp/robot-moveit.l, pr2eus_moveit/test/test-pr2eus-moveit.l
Include #373 
`start-offset-time` should only affect time stamp of trajectory, which is set in `:send-trajectory`.
We don't need to set it in `trajectory-filter`.
- Current state without this PR:
Total time of trajectory becomes `start-offset-time`[s] + `total-time`[ms].
The execution of first trajectory point takes original `time_from_start` + `start-offset-time`.
As `start-offset-time` also affects time stamp of trajectory, trajectory finishes `start-offset-time` * 2 + `total-time` after calling `:angle-vector-motion-plan`.
```
3.irteusgl$ send *ri* :angle-vector-motion-plan (send *baxter* :angle-vector) :start-offset-time 5 :total-time 1000 :ctype :default-controller :move-arm :arms :clear-velocities t
[ INFO] [1534232819.952439981]: [/default_robot_interface_1534232610481270195] …
```
=> Fix :trajectory-filter to ignore start-offset-time

pr2eus_moveit/euslisp/robot-moveit.l, pr2eus_moveit/test/test-pr2eus-moveit.l
Include #372 
When I use `:angle-vector-motion-plan` in pr2eus_moveit with list of two angle-vectors, the last angle-vector is skipped.
This is because trajectory points for second angle-vector starts from `time_from_start: 0` again.
I add test to detect this bug and fix.
```
$ rostopic echo /robot/limb/left/follow_joint_trajectory/goal 
header: 
seq: 1
stamp: 
secs: 1534242824
nsecs: 729660623
frame_id: ''
goal_id: 
stamp: 
secs: 0
nsecs:         0
id: 1534242820729731921_/default_robot_interface_1534239753379624356_80342_/robot/limb/left/follow_joint_trajectory_12
goal: 
trajectory: 
header: 
seq: 1
stamp: 
secs: 1534242824
nsecs: 729660623
frame_id: ''
joint_names: ['left_s0', 'left_s1', 'left_e0', 'left_e1', 'left_w0', 'left_w1', 'left_w2']
points: 
- 
positions: [1.2676694342046062, …
```
=> Fix time_from_start in motion-planned angle-vector-sequence

pr2eus/robot-interface.l, pr2eus/test/default-ri-test.l, pr2eus/test/pr2-ri-test.l
Fixes #354 
Includes #378 
cc @Affonso-Gui
=> Equalize min-time behavior of end-coords-interpolation to usual angle-vector

pr2eus/test/default-ri-test.l, pr2eus/test/pr2-ri-test.l
Included in #355 
- Add simple test to avoid eus error in `:angle-vector` with `:end-coords-interpolation t`
- Add test to catch #354 
Travis of this PR will fail due to the latter test.
=> Add end-coords-interpolation test

pr2eus/robot-interface.l
This PR modified the warning message in case of we can not connect to follow joint trajectory server,
because```goal``` topic is not always comming. 
So we should check the ```status``` topic.
=> [pr2eus/robot-interface.l] Modified warning message in case of we can not connect to follow joint trajectory server

pr2eus/robot-interface.l
`:fast` is correct name.
cf. https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/0.3.14/pr2eus/robot-interface.l#L399
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/0.3.14/pr2eus/robot-interface.l#L535
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/0.3.14/pr2eus/robot-interface.l#L549
=> Fix typos in comments about :fast utility in :angle-vector*

pr2eus/robot-interface.l
Apparently we can reproduce the confirmation behavior of the (unused)`:angle-vector-safe` by setting the (even more unused) `warningp` flag. By doing so, when about to move the real robot a confirmation prompt pops out asking if that is really what we want.
However, when using the `warningp` this prompt is inverted, so saying that you do NOT want the robot to move make it move:
```lisp
(send *ri* :warningp t)
(send *ri* :angle-vector (send *pr2* :init-pose) 5000)
Are you sure to move the real robot? (l_arm_controller/follow_joint_trajectory) (YES or NO): no
Are you sure to move the real robot? (r_arm_controller/follow_joint_trajectory) (YES or NO): no
Are you sure to move the real robot? (head_traj_controller/follow_joint_trajectory) (YES or NO): no
Are you sure to move the real robot? …
```
=> Fix confirmation on warningp

pr2eus/robot-interface.l
`clear-costmap` function and `:clear-costmap` method, whose namespace was fixed in #343, always return `t` even if a service call failed.
In this PR the function returns `t` after calling that service, and otherwise (if the service is not advertised yet) returns `nil`.
=> Fix return value of clear-costmap function

pr2eus/robot-interface.l
The `:stop-motion` stops the current angle vector by sending the actual angle vector as a new command (and therefore overwriting the old command).
The problem is that is also does that when there is no ongoing action, and since it also have an `:wait-interpolation` it takes a few seconds to return from the call.
In this PR we:
1. Only overwrite commands when there are ongoing actions
1. Add a `wait` key argument to the `:stop-motion`, so the user can opt not to wait-interpolation.
@pazeshun
=> Updates to :stop-motion

pr2eus_moveit/test/test-pr2eus-moveit.l
I added test for `collision-object-publisher`
In the test, PR2 moves left arm between blocks.
PQP collision check is executed during the interpolation.
Before move
After move
=> [pr2eus_moveit] Add test for collision-object-publisher

pr2eus/make-pr2-model-file.l, pr2eus/test/pr2-ri-test-simple.l
follow ups of #426
as https://github.com/jsk-ros-pkg/jsk_robot/issues/1407#issuecomment-971313512 reported, it breaks existing API
=> add test code for (pr2) and (instance pr2-robot :init) (instance r2-sensor-robot :init)

pr2eus_moveit/euslisp/collision-object-publisher.l, pr2eus_moveit/test/test-pr2eus-moveit-sim.l, pr2eus_moveit/test/test-pr2eus-moveit-sim.test
add test code to check check apply_planning_scene before creating collision-object-publisher/*ci*
Closes #446
=> test check apply_planning_scene before creating collision-object-publisher/*ci* without MoveIt

pr2eus_tutorials/euslisp/pr2-tabletop-object-grasp.l
In the pr2 grasping tutorials, the usage of `look-at-hand` is wrong.
Here is the simulation outcome that PR2 looks at rarm when grasping.
Here is the real outcome that PR2 looks at rarm when grasping.
=> [pr2eus_tutorials] fix look-at-hand

pr2eus/robot-interface.l
Solution for https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/485.
> if we need to install all action client, may be we try to find them from program code
I have taken this approach, searching and stopping all instances of `ros::simple-action-client` registered as slots in the robot-interface instance.
https://github.com/Affonso-Gui/roseus_resume/blob/eus10/euslisp/interruption-handler.l#L60-L70
The initialization code is then moved to `robot-interface`, and can be enabled by default in other robots without any modification. Roseus_resume will be automatically disabled on eus9 or when the package is not found, and can also be manually disabled by setting the `*enable-roseus-resume*` variable to `nil`.
```lisp
(setq *enable-roseus-resume* nil)
(pr2-init)
```
Other (user-defined) actions can …
=> Add roseus_resume support

pr2eus/speak.l
Now, when we execute something like `(send *ri* :speak-jp "こんにちは")`, sound action goal topic has no headertimestamp.
I fixed it in this PR.
```
$ rostopic echo /robotsound_jp/goal
header: 
seq: 0
stamp: 
secs: 0
nsecs:         0
frame_id: ''
goal_id: 
stamp: 
secs: 0
nsecs:         0
id: "1686130902134708426_/fetch_eus_interface_1686130898541295371_2753725_robotsound_jp_0"
goal: 
sound_request: 
sound: -3
command: 1
volume: 1.0
arg: "\u3053\u3053\u304Cdock\u3067\u3059"
arg2: "ja"
```
=> [pr2eus] Add header timestamp to actiongoal topic in play-sound

.github/workflows/config.yml, pr2eus_tutorials/package.xml
- fix CI: update jsk_travis 0.5.27, override node20 https://github.com/actions/upload-artifact/issues/616#issuecomment-2350667347, see https://github.com/jsk-ros-pkg/jsk_common/pull/1808
- pr2eus_tutorials: move jsk_pcl_ros from build_depend to run_depend
=> Fix github action

pr2eus_moveit/euslisp/collision-object-publisher.l
The centor of primitvie cylinder is not matched between eus and moveit.
I added transformation code to align the center of the EUS model with the MoveIt model in the definition of the pose for the cylinder's solid primitive messages.
refer to following figures 
in eus 
in moveit (only cylinder models are not matched.)
PR
=> [pr2eus_moveit] align the center of primitive cylinder between eus and moveit
