.rosinstall
update to latest .travis, this will take over #90
=> Remove packages from .rosinstall on travis

pr2eus/robot-interface.l
Copy the function from jsk_calibration and use it.
Tested on baxter
=> Use angle vector duration when no time is set.

pr2eus/pr2-interface.l
to enhance the consistency between when simulation mode and when not.
=> return list of t at :wait-interpolation on simulation mode

pr2eus/robot-interface.l
From https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/85#discussion_r23537288
How can I confirmed whether the document will be made correctly or not?
=> [pr2eus] Repair :angle-vector args document

pr2eus/robot-interface.l
see https://github.com/jsk-ros-pkg/jsk_visualization/issues/227
It's important to write code independent from robot!
=> [pr2eus] Add make-robot-interface-from-name function to create robot-interface instance from name

pr2eus/package.xml
```
sudo aptitude show ros-indigo-pr2eus                                                                
パッケージ: ros-indigo-pr2eus            
新規: はい
状態: インストール済み
自動的にインストールされた: はい
バージョン: 0.1.7-0trusty-20150211-0608-+0000
優先度: 特別
セクション: misc
メンテナ: furuta <k-okada@jsk.t.u-tokyo.ac.jp>
アーキテクチャ: amd64
展開サイズ: 34.4 M
依存: ros-indigo-control-msgs, ros-indigo-dynamic-reconfigure, ros-indigo-euscollada, ros-indigo-move-base-msgs, ros-indigo-nav-msgs, ros-indigo-roseus, ros-indigo-rostest,
ros-indigo-sound-play
競合: ros-indigo-pr2eus
説明: pr2eus
ホームページ: http://ros.org/wiki/pr2eus
```
=> Modify wrong maintainer and author name.

pr2eus/robot-interface.l
Add euslisp implementation mannequin mode.
=> Add euslisp implementation mannequin mode.

pr2eus/robot-interface.l
add method for checking large rotation and fast moving before sending command to the robot
=> add :angle-vector-safe for prototype robot

pr2eus/robot-interface.l
@aginika Please check if this works
=> [pr2eus] Support ctype in :angle-vector-duration

pr2eus/catkin.cmake, pr2eus/robot-interface.l, pr2eus/test/pr2-ri-test-simple.l, pr2eus/test/pr2-ri-test-simple.launch
- [test/pr2-ri-test-simple.{l,launch}] add test code for angle-vector-duration
- [robot-interfce.l] fix :angle-vector-duration for limb contorller
=> fix :angle-vector-duration for limb controller, this will fix #113

pr2eus/robot-interface.l
=> [jsk_pr2eus] FIx :angle-vector-sequence by passing ctype argument to :angle-vector-duration

pr2eus/pr2-interface.l
see https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/160#issuecomment-128637198
=> pr2-interface.l : add go-pos-no-wait and go-wait

pr2eus/robot-interface.l, pr2eus/test/default-ri-test.l
```
(load "models/room610-scene.l")
(room610)
(setq *ri* (instance sample-robot-interface :init :objects (send *room610* :objects)))
(assert (send *ri* :objects) "robot-interface :objects")
```
=> [test/default-ri-test.l] add test for :objects methods

pr2eus/pr2-interface.l
This change is for after hydro.
=> [pr2eus] change-inflation-range to use new service name

pr2eus/pr2-interface.l
along with https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/164
=> [pr2eus/pr2-interface.l] fix return value of `:go-pos-unsafe-wait`

pr2eus/speak.l
- super easy to read code
- support wait and timeout for every speaking
- support multi language with google engine
=> [pr2eus/speak.l] refactor speak.l

pr2eus/robot-interface.l, pr2eus/test/default-ri-test.l
ref: https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/178#issuecomment-153002164
=> [pr2eus/robot-interface.l] add method :find-object to robot-interface and test code

pr2eus/pr2-interface.l, pr2eus/robot-interface.l
```lisp
3.irteusgl$ send *ri* :state :gripper :rarm
86.7216
;;;;;;;;;;;;;;;;;;;;;;;;  gripper closed by another node ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
4.irteusgl$ send *ri* :update-robot-state
(0.529944 -0.345858 0.345858 0.114356 -0.072519 0.072519 0.463004 -0.301232 0.298442 -0.039049 0.025103 -0.025103 2\
58.551 0.0 0.052455 1.65193 -0.2075 -0.067929 0.220879 -1.19059 -0.056001 -0.674988 -0.487202 0.16348 -10.055 -1.83\
548 -1.83548 -1.83548 -1.83548 0.0 0.0 -0.146687 0.443662 0.171684 0.00487 -0.472164 -0.619928 -0.173191 0.0 0.0 0.\
0 0.0 0.0 0.0 0.0)
5.irteusgl$ send *ri* :state :gripper :rarm
1.01155
```
c.f. https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/181
=> [pr2eus/pr2-interface.l] add :state :gripper method

.travis.yml
travis keep failing aftter #200
=> update to use travis 0.2.4

pr2eus/pr2-interface.l
according with the change of default value https://github.com/jsk-ros-pkg/jsk_robot/pull/535
=> [pr2eus/pr2-interface.l] default argument of change-inflation-range 0.55 -> 0.2

pr2eus/pr2-interface.l, pr2eus/robot-interface.l
related https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/190
I commited different branch with tested on real robot.
This PR fixes the topic to fetch gripper information, and accessor to it.
=> [pr2eus/pr2-interface.l] fix gripper method

.travis.yml
sometimes the test fails... not sure why...
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_pr2eus-indigo-deb-true/268/consoleFull -> ok
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_pr2eus-indigo-deb-true/267/console -> ng
=> set test parallel to 1

pr2eus_tutorials/README.md, pr2eus_tutorials/config/hrp2jsk_reach_object.rviz, pr2eus_tutorials/config/pr2_reach_object.rviz, pr2eus_tutorials/euslisp/reach-object.l, pr2eus_tutorials/euslisp/robot-setup.l, pr2eus_tutorials/package.xml
this contains https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/213.
=> [pr2eus_tutorial] Add tutorial demo to reach object

pr2eus/robot-interface.l
=> robot-interface.l : need a consistency of controller order in the the entry of controller-table fix #227

pr2eus/robot-interface.l
@pazeshun this may solve your problem, sometimes `:spin-once` in `:wait-interpolation` (or `:interpolating-smoothp` more precise) did not catch new feedback mesasge, and use old one,
=> wait for new feedback message arrival for :wait-interpolation-smooth

pr2eus/robot-interface.l, pr2eus/test/default-ri-test.l
sometines :state .. :wait-unitl-update t did not returns
c.f.: see test in https://github.com/jsk-ros-pkg/jsk_robot/pull/627
=> add test-state-wait-until-update

pr2eus/speak.l
prevents creating action client everytime speaking
=> [pr2eus/speak.l] use single speak-action-client

pr2eus/robot-interface.l
=> fix :wait-intepolation-smooth for SinglePointJointAcionGoal

pr2eus_moveit/euslisp/robot-moveit.l
@YoheiKakiuchi, please review. This PR incldues several changes in robot motion
1. :angle-vector-motion-plan send trajectory not only joints incldues move-arm
2. :angle-vector-motion-plan has new arguments, named :total time, which scales planned motion duration
3. :add :start-offset-time, which adde start offet to trajecotry (for fetch)
=> fix robot-moveit.l

pr2eus/robot-interface.l, pr2eus_moveit/euslisp/robot-moveit.l
- :trajectory-filter add clear-velocities
- robot-interface.l: send-trajectory-each : check if vels/effs is #f()
=> :trajectory-filter add clear-velocities option

pr2eus/robot-interface.l
=> [pr2eus] Add end-coords-interpolation

pr2eus_moveit/euslisp/robot-moveit.l
=> [pr2eus_moveit] fix typo in :angle-vector-motion-plan

.travis.yml
- enable jade / kinetic test
- move some common variables to global
=> [.travis.yml] enable jade / kinetic (but allow_failure)

pr2eus/robot-interface.l, pr2eus/test/default-ri-test.l, pr2eus/test/pr2-ri-test-simple.l
some function does not return expected return values written at docstring. In this pull request, I fixed behaviors by implementing some functions for simulation mode and test codes.
=> [pr2eus] fix some funcs that break behaviors written at docs

pr2eus_moveit/euslisp/collision-object-publisher.l
reporeted at https://github.com/jsk-ros-pkg/jsk_robot/issues/756#issuecomment-285552552
=> advertise CollisionObject with latch=t

pr2eus/robot-interface.l
c.f. https://github.com/jsk-ros-pkg/jsk_robot/pull/791#pullrequestreview-45324124
=> add tms comment to :angle-vector-sequence

pr2eus/robot-interface.l
- `:cancel-angle-vector` by `controller-type`
- fix typo in `robot-interface.l`
=> [pr2eus] enable controller-type in :cancel-angle-vector

pr2eus_moveit/euslisp/robot-moveit.l
Reverts jsk-ros-pkg/jsk_pr2eus#310
=> Revert "[pr2eus_moveit] fix typo in total-time condition"

pr2eus/robot-interface.l, pr2eus/test/pr2-read-state-test.l
before:
```lisp
(send *ri* :state :odom :pose :wait-until-update t)
;; nil
```
after:
```lisp
(send *ri* :state :odom :pose :wait-until-update t)
;; coodinates
```
=> [pr2eus] do not pass :wait-until-update in :state args

pr2eus_moveit/test/test-pr2eus-moveit.l
Included in #361 
Extract test code from #361 .
Travis of this PR will fail.
=> Add test for start-offset-time

pr2eus_moveit/test/test-pr2eus-moveit.l
Included in #363 
Extract test code from #363 .
Travis of this PR will fail.
=> Add test for concatenation in :angle-vector-make-trajectory 

pr2eus/test/speak-test-action.py, pr2eus/test/speak-test.py, pr2eus/test/speak-test.test
- add test for action interface
- add speak-test.py to check contents of SpeakRequest message
- run speak-test.l and catch message by hztest
=> add test for pr2/speak.l

pr2eus/speak.l, pr2eus/test/speak-test-action.py, pr2eus/test/speak-test.l
Check #366 (play-sound could not play file format)
=> add test to reproduce #366 (play-sound could not play file format)

pr2eus/test/speak-test.l
Fixed #368 
I added a volume key value.
This function is enabled for indigo and kinetic user.
=> [pr2eus/speak.l] Fixed #368. When sound_play::SoundRequest has a :volume slot, set volume value.

pr2eus/pr2-interface.l
* add get-grasp-result method
* add :wait key to start-grasp method
(resolved version of #209, Close #209)
=> [pr2eus] add :get-grasp-result methody and :wait key to :start-grasp method

pr2eus_tutorials/README.md
I update `pr2eus_tutorials` readme
- add more information for `kinetic` users
- fix typo
- format README
=> Update pr2eus_tutorials README

pr2eus/pr2-interface.l
https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/397
=> Avoid unnecessary convex-hull-3d calculation on :start-grasp

.travis.yml
Upload apt-cacher-ng cache to server.
This PR includes #414 .
=> Upload apt cache

pr2eus/pr2-interface.l, pr2eus/robot-interface.l, pr2eus/test/pr2-ri-test-base.l, pr2eus/test/pr2-ri-test-simple.l, pr2eus/test/pr2-ri-test.launch
need to add static_transform_publisher 0 0 0 0 0 0 /world /map 100 to provide '/world'
add test to check `:go-pos-unsafe-no-wait` and that error is fixed by #428
Closes #428
=> add pr2-ri-test-simple.l to test/pr2-ri-test.launch

pr2eus/test/pr2-ri-test-arm.l
=> Add test for #422

pr2eus/robot-interface.l
add `:volume` argument in `robot-interface` `:speak` methods.
=> [pr2eus] add volume key arg for robot-interface :speak
